version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  estocks-command-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
    # ports:
    #   - 3306:3306
    # expose:
    #   - 3306
    volumes:
      - mysqldb:/var/lib/mysql

  estocks-query-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  estocks-eureka-server:
    image: estocks-eureka-server
    build: stocksmicroservices_v3/estocks-eureka-server/.
    ports:
      - 8761:8761
        
  estocks-cloud-gateway:
    image: estocks-cloud-gateway
    build: stocksmicroservices_v3/estocks-cloud-gateway/.
    ports:
      - 5000:5000
    links:
      - estocks-eureka-server
      - estocks-auth-api
      - estocks-query-api
      - estocks-command-api

  estocks-auth-api:
    image: estocks-auth-api
    build: stocksmicroservices_v3/estocks-auth-api/.
    ports:
      - 5300:5300
    links:
      - estocks-eureka-server
      
  estocks-query-api:
    image: estocks-query-api
    build: stocksmicroservices_v3/estocks-query-api/.
    ports:
      - 5200:5200
    depends_on:
      - estocks-query-db
    links:
      - estocks-eureka-server
      - estocks-query-db
      
  estocks-command-api:
    image: estocks-command-api
    build: stocksmicroservices_v3/estocks-command-api/.
    ports:
      - 5100:5100
    depends_on:
      - estocks-command-db
    links:
      - estocks-eureka-server
      - estocks-command-db

volumes:
  mysqldb:
  mongodb: